[2023-09-17T14:17:45.017+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.executaCrawler manual__2023-09-17T14:17:43.647960+00:00 [queued]>
[2023-09-17T14:17:45.027+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.executaCrawler manual__2023-09-17T14:17:43.647960+00:00 [queued]>
[2023-09-17T14:17:45.027+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-17T14:17:45.044+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): executaCrawler> on 2023-09-17 14:17:43.647960+00:00
[2023-09-17T14:17:45.048+0000] {standard_task_runner.py:57} INFO - Started process 1143 to run task
[2023-09-17T14:17:45.051+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl', 'executaCrawler', 'manual__2023-09-17T14:17:43.647960+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpbsyo_zxd']
[2023-09-17T14:17:45.054+0000] {standard_task_runner.py:85} INFO - Job 143: Subtask executaCrawler
[2023-09-17T14:17:45.097+0000] {task_command.py:415} INFO - Running <TaskInstance: etl.executaCrawler manual__2023-09-17T14:17:43.647960+00:00 [running]> on host 930ac20b04d8
[2023-09-17T14:17:45.327+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='executaCrawler' AIRFLOW_CTX_EXECUTION_DATE='2023-09-17T14:17:43.647960+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-17T14:17:43.647960+00:00'
[2023-09-17T14:17:45.328+0000] {logging_mixin.py:151} INFO - Executando o crawler...
[2023-09-17T14:17:45.328+0000] {logging_mixin.py:151} INFO - Requisitando a Rota: '/json_empenhos'
[2023-09-17T14:17:45.337+0000] {logging_mixin.py:151} INFO - URL: https://trescoracoes-mg.portaltp.com.br/api/transparencia.asmx/json_empenhos?ano=2023&mes=7
[2023-09-17T14:17:46.232+0000] {logging_mixin.py:151} INFO - Inserindo dados no banco de dados...
[2023-09-17T14:17:46.397+0000] {logging_mixin.py:151} INFO - Dados inseridos com sucesso!
[2023-09-17T14:17:46.399+0000] {logging_mixin.py:151} INFO - Rota '/json_empenhos' requisitada com sucesso! Aguardando 60 segundos para a próxima requisição...'
[2023-09-17T14:18:46.435+0000] {logging_mixin.py:151} INFO - Requisitando a Rota: '/json_liquidacoes'
[2023-09-17T14:18:46.452+0000] {logging_mixin.py:151} INFO - URL: https://trescoracoes-mg.portaltp.com.br/api/transparencia.asmx/json_liquidacoes?ano=2023&mes=7
[2023-09-17T14:18:47.509+0000] {logging_mixin.py:151} INFO - Inserindo dados no banco de dados...
[2023-09-17T14:18:47.700+0000] {logging_mixin.py:151} INFO - Dados inseridos com sucesso!
[2023-09-17T14:18:47.702+0000] {logging_mixin.py:151} INFO - Rota '/json_liquidacoes' requisitada com sucesso! Aguardando 60 segundos para a próxima requisição...'
[2023-09-17T14:19:47.760+0000] {logging_mixin.py:151} INFO - Requisitando a Rota: '/json_pagamentos'
[2023-09-17T14:19:47.767+0000] {logging_mixin.py:151} INFO - URL: https://trescoracoes-mg.portaltp.com.br/api/transparencia.asmx/json_pagamentos?ano=2023&mes=7
[2023-09-17T14:19:48.761+0000] {logging_mixin.py:151} INFO - Inserindo dados no banco de dados...
[2023-09-17T14:19:48.796+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DependentObjectsStillExist: cannot drop table json_pagamentos because other objects depend on it
DETAIL:  view warehouse.stg_pagamentos depends on table json_pagamentos
HINT:  Use DROP ... CASCADE to drop the dependent objects too.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 9, in executaCrawler
    main()
  File "/opt/airflow/dags/crawler.py", line 102, in main
    report.run()
  File "/opt/airflow/dags/crawler.py", line 68, in run
    self.insereDados()
  File "/opt/airflow/dags/crawler.py", line 62, in insereDados
    df.to_sql(f"{str(self.__path).replace('/','')}", con=engine, if_exists='replace', index=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2878, in to_sql
    return sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 769, in to_sql
    return pandas_sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1910, in to_sql
    table = self.prep_table(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1814, in prep_table
    table.create()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 907, in create
    self.pd_sql.drop_table(self.name, self.schema)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1963, in drop_table
    self.get_table(table_name, schema).drop(bind=self.con)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 979, in drop
    bind._run_ddl_visitor(ddl.SchemaDropper, self, checkfirst=checkfirst)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2221, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 1106, in visit_table
    self.connection.execute(DropTable(table))
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1477, in _execute_ddl
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.errors.DependentObjectsStillExist) cannot drop table json_pagamentos because other objects depend on it
DETAIL:  view warehouse.stg_pagamentos depends on table json_pagamentos
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

[SQL: 
DROP TABLE json_pagamentos]
(Background on this error at: https://sqlalche.me/e/14/2j85)
[2023-09-17T14:19:48.815+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=etl, task_id=executaCrawler, execution_date=20230917T141743, start_date=20230917T141745, end_date=20230917T141948
[2023-09-17T14:19:48.835+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 143 for task executaCrawler ((psycopg2.errors.DependentObjectsStillExist) cannot drop table json_pagamentos because other objects depend on it
DETAIL:  view warehouse.stg_pagamentos depends on table json_pagamentos
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

[SQL: 
DROP TABLE json_pagamentos]
(Background on this error at: https://sqlalche.me/e/14/2j85); 1143)
[2023-09-17T14:19:48.862+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-17T14:19:48.885+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
